name: Build and deploy to AWS Lambda
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm ci
    - name: Archive bundle
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./bundle.zip ./
    - name: Deploy to Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_region: ${{ secrets.AWS_REGION }}
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        function_name: ${{ AWS_FUNCTION_NAME }}
        zip_file: bundle.zip
